baseURL: "https://cboone.github.io/"
title: Christopher Boone
enableInlineShortcodes: true

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

outputs:
  home:
    - HTML
    - JSON
    - RSS

enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  section: sections
  tag: tags

menu:
  main:
    - name: LLMs
      url: llms/
      weight: 1
    # - name: Math
    #   url: math/
    #   weight: 2
    - name: Projects
      url: projects/
      weight: 3
    - name: Search
      url: search/
      weight: 5
    - name: Tools
      url: tools/
      weight: 4

params:
  author: Christopher Boone

  MainSections: ["posts"]

  DateFormat: "January 2006"

  comments: false
  defaultTheme: auto
  disableAnchoredHeadings: true
  disableScrollToTop: false
  disableSpecial1stPost: true
  disableThemeToggle: false
  hideFooter: false
  math: true

  ShowAllPagesInArchive: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowPostNavLinks: false
  ShowReadingTime: false
  ShowShareButtons: false

  ShowWordCount: false

  ShowToc: false
  TocOpen: true
  UseHugoToc: true

  profileMode:
    enabled: true

    title: Christopher Boone
    subtitle: "Hands on generalist."

    imageUrl: "profile.png"
    imageTitle: Christopher Boone
    imageHeight: 160
    imageWidth: 160

    buttons:
      - name: LLMs
        url: llms/
      # - name: Math
      #   url: math/
      - name: Projects
        url: projects/
      - name: Tools
        url: tools/
      - name: Search
        url: search/

  socialIcons:
    - name: GitHub
      url: https://github.com/cboone
    - name: Instagram
      url: https://instagram.com/catamounthardware
    - name: LinkedIn
      url: https://linkedin.com/in/cboone
    - name: SoundCloud
      url: https://soundcloud.com/cboone
    - name: Spotify
      url: https://open.spotify.com/artist/2weE50JXxHzKpjVNr4fQiH
    - name: AppleMusic
      url: https://music.apple.com/artist/christopher-boone/1801335941

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    icon: favicon.ico
    iconHeight: 18
    text: "Christopher Boone"

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    noClasses: false

  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
